/****** Script de la commande SelectTopNRows à partir de SSMS  ******/
SELECT TOP (1000) [id_lieu]
      ,[id_local]
      ,[nom_lieu]
      ,[ad_lieu]
      ,[com_lieu]
      ,[insee]
      ,[typee]
      ,[date_maj]
      ,[ouvert]
      ,[sourcee]
      ,[Xlong]
      ,[Ylat]
      ,[nbre_pl]
      ,[nbre_pmr]
      ,[duree]
      ,[horaires]
      ,[proprio]
      ,[lumiere]
      ,[comm]
  FROM [ods].[dbo].[BNLC]