--data the ODS  database

--CREATE DATABASE ODS;

--create the DWH database

--CREATE DATABASE DWH;

CREATE TABLE ODS.dbo.BNLC(
	ID_LIEU VARCHAR(MAX),
	ID_LOCAL VARCHAR(MAX),
	NOM_LIEU VARCHAR(MAX),
	AD_LIEU VARCHAR(MAX),
	COM_LIEU VARCHAR(MAX),
	INSEE VARCHAR(MAX),
	TPE VARCHAR(MAX),
	DATE_MAJ VARCHAR(MAX),
	OUVERT VARCHAR(MAX),
	SOURCE VARCHAR(MAX),
	XLONG VARCHAR(MAX),
	YLAT VARCHAR(MAX),
	NBRE_PL VARCHAR(MAX),
	NBRE_PMR VARCHAR(MAX),
	DUREE VARCHAR(MAX),
	HORAIRES VARCHAR(MAX),
	PROPRIO VARCHAR(MAX)

);

TRUNCATE TABLE ODS.dbo.BNLC ;

BULK INSERT ODS.dbo.BNLC
FROM 'C:\Users\aisse\Downloads'
WITH 
(
	FORMAT='CSV',
	FIRSTROW=2
)

